In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2025-10-18 23:27:27.520351: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-18 23:27:27.579389: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-18 23:27:29.182637: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


TensorFlow version: 2.20.0


In [19]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/home/exlley/projects/machine-learning/.venv/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
E0000 00:00:1760841039.252360   18043 cuda_executor.cc:1309] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1760841039.266473   18043 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.06028923, -0.03824568, -0.56787074,  0.24839792, -0.2731237 ,
        -0.99069124, -0.8982521 , -0.33163875, -0.5509552 , -0.9280027 ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.14954697, 0.13551408, 0.07979418, 0.18049791, 0.10714656,
        0.05228085, 0.05734405, 0.10105679, 0.08115542, 0.05566316]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.9511251)

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9166 - loss: 0.2914
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9575 - loss: 0.1429
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9668 - loss: 0.1087
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9724 - loss: 0.0884
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9764 - loss: 0.0766


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9760 - loss: 0.0760


[0.07598674297332764, 0.9760000109672546]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.2692238e-08, 1.4725598e-08, 7.3058154e-06, 2.7806096e-04,
        2.5196683e-11, 3.7249228e-07, 7.0976245e-15, 9.9970776e-01,
        1.9886641e-06, 4.4142494e-06],
       [8.7457408e-07, 1.5427446e-04, 9.9981111e-01, 3.2016153e-05,
        2.3061642e-13, 8.4737775e-07, 1.3003464e-07, 5.6992930e-13,
        8.1032198e-07, 1.4027095e-11],
       [1.3996620e-06, 9.9903595e-01, 5.8330348e-05, 8.4522544e-06,
        1.1617812e-04, 3.9931870e-06, 8.8725348e-05, 5.2707433e-04,
        1.5691041e-04, 2.8758500e-06],
       [9.9982762e-01, 1.1968050e-09, 4.9632032e-05, 2.1603917e-06,
        4.5161650e-07, 2.0714686e-05, 9.5729396e-05, 3.1456993e-06,
        1.7872974e-08, 4.3783780e-07],
       [1.8812498e-05, 3.3016831e-09, 4.0842792e-06, 5.7778482e-07,
        9.8180354e-01, 2.0154052e-05, 1.2737412e-04, 5.1049232e-05,
        8.1040853e-05, 1.7893352e-02]], dtype=float32)>